### ISSUE TITLE
Store user-supplied fortunes

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#10]
Probably use `localStorage`

**Comment by christiansulaiman** [comment]
The localStorage is updating at a delayed rate. For example, if I changed a fortune, it is not stored immediately but rather after another fortune is updated. Idk if its an issue with localStorage or not.

**Comment by phentos** [comment]
localStorage is synchronous so that must be our fault

**Comment by samw0627** [comment]
It looks like the fortunes are saved to storage before it is updated to the user-entered ones.

**Comment by samw0627** [comment]
Do you think we should make it so that we store all the fortunes when the user starts interacting with the origami? Instead of storing it to local storage everytime it the sidebar is updated?
