### ISSUE TITLE
Prepare ADR for choosing paper origami fortune teller

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#18]
see [Choosing-Origami-Fortune-Teller.md](https://github.com/cse110-sp23-group1/cse110-sp23-group1/blob/main/specs/adrs/050523-Choosing-Origami-Fortune-Teller.md)

**Comment by christiansulaiman** [comment]
Minor bug in the Markdown preview where it says:
Error in user YAML: (<unknown>): mapping values are not allowed in this context at line 5 column 24

**Comment by phentos** [comment]
thanks for the writeup @christiansulaiman !
