### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by AlbertXDing** [cse110-sp23-group1/Origami-Fortune-Teller#2]
A vertical stack of 8 boxes pre-filled with text (for visual, see [Figma](https://www.figma.com/file/38Z0erfGU10hFsjoErmDuD/Wireframes-v.1-(fortune-teller)?type=design&node-id=2-2&t=FfQY52hu6GfemhpE-0
)) to represent the fortunes written in the origami.

**Comment by phentos** [comment]
duplicate of #3
