### ISSUE TITLE
SVG's need cleanup

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#20]
At a minimum there is excess whitespace, but make a pass for quality generally. SVG's are on [core-svg-handler](https://github.com/cse110-sp23-group1/Oragami-Fortune-Teller/tree/core-svg-handler).

S/S courtesy @lmeiucsd 
<img width="218" alt="Screen Shot 2023-05-16 at 11 09 16 AM" src="https://github.com/cse110-sp23-group1/Oragami-Fortune-Teller/assets/88351375/3cac9c7d-28a1-431c-8b2e-e7ee6c305201">

**Comment by lmeiucsd** [comment]
Found a [website](https://svgcrop.com/) that will remove the excess whitespace from SVGs, here is a screenshot showing the cropped result of closed.svg:





![Image](https://github.com/cse110-sp23-group1/Oragami-Fortune-Teller/assets/88351375/e4a15cf5-30a6-4c8e-8d1c-086b7b647d82)

**Comment by lmeiucsd** [comment]
It looks like there's still whitespace still in the image preview above, but when viewing the image, there seems to be no whitespace.

**Comment by phentos** [comment]
I think there is still more to do, in the sense that the SVG files themselves are essentially unreadable -- would really benefit from commenting what things are and so on
