### ISSUE TITLE
Adjust new fortune input behavior

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#23]
We don't replace `textContent` before or after the user gives a value, meaning every time they edit it will be prefilled with the last thing they submitted. Imo, it should have the fortune they are currently editing instead -- warrants discussion and an ADR @adarsh249

_Originally posted by @phentos in https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/pull/15#discussion_r1197145472_

- [x] new fortune input textContent initial launch behavior
- [x] #24

**Comment by phentos** [comment]
also, the user can't cancel. should be able to click out (anywhere not in the input field), press `esc`, back swipe etc

**Comment by phentos** [comment]
also, as another side effect to this, every fortune that has ever been editted is changed to the new entry submitted lol

**Comment by adarsh249** [comment]
> also, as another side effect to this, every fortune that has ever been edited is changed to the new entry submitted lol
Just to be more specific, if you click on a fortune, edit it, then click every other fortune and hit save again it changes all of them.

**Comment by AlbertXDing** [comment]
Has this already been fixed? If so, where can I see it?

**Comment by adarsh249** [comment]
Yes, has been fixed on complete-core-fortune-sidebar-functionality branch. My only issue is if you edit the input and click escape, the input should not save as a new input, it should go back to whatever was there before.
