### ISSUE TITLE
Fortune input process should update the selected fortune bar entry

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#25]

**Comment by phentos** [comment]
Since this hinges on the final sidebar implementation model, this is effectively blocked at this time

**Comment by adarsh249** [comment]
working on e2e firsts, not sure unit testing will be the best practice for our code... will get clarification by tuesday.

**Comment by phentos** [comment]
test targeted is not unit testable under current paradigm, converting to e2e

**Comment by adarsh249** [comment]
wait hold up, unit tests are required for the grade, so we might have to change smth or just try to write as much as we can?

**Comment by phentos** [comment]
that's a different thing, point here is that the specific test of 'new fortune inputs go into the originally clicked fortune box' can't be done with our implementation since we didn't set up the sidebar class. what we have right now can only be tested using end to end methods
