### ISSUE TITLE
Move to loading default fortunes from json

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#32]
file already created at `/assets/fortunes.json`, currently we're using an array declared in `main.js` instead

**Comment by zsiyed** [comment]
@phentos do you just want to replace the array in main with a few lines that read in the json file and access fortunes.english.default?

**Comment by phentos** [comment]
ideally imo the page load and/or page handler (#13) would call a function with the user's language as a parameter, that would then get checked against available languages and the appropriate array would then be handed off to the sidebar class

so strictly in support of this issue in isolation, yeah, i think just a helper function a la `fetchFortunes` would be sufficient -- the language choice / fortune set decision is technically beyond the scope here. 

would be a convenient place to touch on #10 though since we'd want to use local fortunes anyway if they exist
