### ISSUE TITLE
Migrate subelement styles into indepedent sheets?

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#39]
It may be worth migrating subelement specific styles into their own sheet at some point -- for example, move `.sidebar` styles into `SideBar.css` then add an `@import "SideBar.css"` to the top of `main.css`

Would make our CSS more maintainable/readable

**Comment by AlbertXDing** [comment]
I think for now it's ok because it's still pretty easy to see each part, but If we keep adding stuff this would be a good idea.
