### ISSUE TITLE
Create Final Figma SVG Mockup

### ISSUE THREAD

**Issue by adarsh249** [cse110-sp23-group1/Origami-Fortune-Teller#47]
Need to create the last Figma mockup. AKA the beautified version of the last fortune teller on [here](https://www.figma.com/file/38Z0erfGU10hFsjoErmDuD/Wireframes-v.1-(fortune-teller)?type=design&node-id=0-1&t=5mHX4epDzsRsJ2Il-0) under Page1.
In addition, the SVGs of vertically-opened and horizontally-opened (ones without nums) need to be resized to the same size as closed and as vertically-opened with nums and horizontally-opened with nums.

**Comment by samw0627** [comment]
Updated all svgs in updated-origami folder

**Comment by phentos** [comment]
This reads to me as two different problems:
- [x] SVG sizes not matching is a property error (only in effect on `core-svg-handler`, not yet merged)
- [x] Create a figma mockup for last fortune teller

**Comment by adarsh249** [comment]
> Updated all svgs in updated-origami folder

did u put them in assets/images/origami or assets/images/origami-with-ids. I've been using the origami-with-ids folder, so we can honestly delete the other one.
@samw0627

**Comment by adarsh249** [comment]
final mockups look good and sizes fixed, closing issue...
