### ISSUE TITLE
Add CSS Hover Feature to Flaps

### ISSUE THREAD

**Issue by adarsh249** [cse110-sp23-group1/Origami-Fortune-Teller#48]
There needs to be a hover feature, such that when the user hovers over the clickable sections, it becomes a darker shade of the current color.
- [x] Add hover CSS to clickable sections on closed fortune teller.
- [x] Add hover CSS to clickable sections on vertically-opened-nums.
- [x] Add hover CSS to clickable sections on horizontally-opened-nums.
- [x] Add hover CSS to clickable sections on open fortune teller.

Refer to svgPaths array in main.js on core-svg-handler branch to see a list of the file paths currently being used for the SVGs.

**Comment by christiansulaiman** [comment]
Me and Salam have figured out how to implement the hover function on the closed fortune teller, should we commit it to the core-svg-handler branch or do we just make a new branch for this issue to not disrupt that branch's progress?

**Comment by lmeiucsd** [comment]
I think you can just commit it to the same branch. I just committed on core-svg-handler, basically added documentation for most existing functions there. So just pull my changes and it should be fine..

**Comment by adarsh249** [comment]
issue edited to include the the open fortune teller

**Comment by adarsh249** [comment]
Closing, works... ty for bug fixing larry
