### ISSUE TITLE
Create buttons to Reset

### ISSUE THREAD

**Issue by adarsh249** [cse110-sp23-group1/Origami-Fortune-Teller#51]
- [ ] Create "Play Again" button  that resets the fortune teller after the user has seen its fortune. This should reset the fortune teller back to its initial state (closed)
- [ ] Create "Reset Fortunes" button that resets all 8 fortunes back to its' presets.

**Comment by samw0627** [comment]
Link to Figma of style and position of Button: 
[Figma Link](https://www.figma.com/file/38Z0erfGU10hFsjoErmDuD/Wireframes-v.1-(fortune-teller)?type=design&node-id=159-1437&t=ii8Dn23xeewKhD73-0)
