### ISSUE TITLE
Add some background for the app

### ISSUE THREAD

**Issue by christiansulaiman** [cse110-sp23-group1/Origami-Fortune-Teller#54]
- [ ] Figure out what sort of background to use (pastel, patterns, something else?)
- [ ] Implement this in CSS

**Comment by phentos** [comment]
options as i see them:
- a scene (a playground, something like that?)
- something that tiles

to implement:
- single image: `<body background="assets/images/someImage.ext">`
- tiled image: `<body background="assets/images/someImage.ext" style="background-repeat: repeat;">`

**Comment by phentos** [comment]
optional vignette layer feature on [vignette-on-background](https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/tree/vignette-on-background) branch
