### ISSUE TITLE
Make all fonts the same

### ISSUE THREAD

**Issue by christiansulaiman** [cse110-sp23-group1/Origami-Fortune-Teller#55]
Decide which font to use and change all text to use the same font

**Comment by adarsh249** [comment]
Looks like the font in Figma or the font @Salam-Aboul-Hosn used for the title may be the one to use.

**Comment by adarsh249** [comment]
assigned to @adarsh249

**Comment by phentos** [comment]
consider implementing on [aesthetics-and-bonus-features](https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/tree/aesthetics-and-bonus-features)

**Comment by phentos** [comment]
Implement along with #68
