### ISSUE TITLE
Generate favicon

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#6]
Need to choose what it should be as well, good candidate is Sam's mockup from [figma](https://www.figma.com/file/38Z0erfGU10hFsjoErmDuD/Wireframes-v.1-(fortune-teller)?type=design&node-id=2-2&t=FfQY52hu6GfemhpE-0).

Can use [my python script](https://github.com/cse110-sp23-group1/magic8ball/blob/main/favicon_io/generate_favicons.py) from 8ball.

**Comment by christiansulaiman** [comment]
Set a favicon for the website over on my branch. If we want a different favicon, we could change it too.

EDIT: Just changed the favicon to the one over on Sam's mockup.
