### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by adarsh249** [cse110-sp23-group1/Origami-Fortune-Teller#61]
Update the README file to include:
- [x] Link to Project
- [x] Link to JS Docs
- [x] Widget for CI/CD Pipeine
- [x] Widget for CodeClimate ( daa3cb5 )
- [x] Description of project
- [x] How to use project

Requires #60 #59 
Feel free to edit these if we should take any off or add more to this.

**Comment by phentos** [comment]
removed version number since that's displayed on the releases sidebar entry

**Comment by Salam-Aboul-Hosn** [comment]
Basically done with the how to use part. Don't want to check it off because I want to add an image of the website when we finish the project
