### ISSUE TITLE
Remove fortune input box while animating

### ISSUE THREAD

**Issue by adarsh249** [cse110-sp23-group1/Origami-Fortune-Teller#63]
If you edit a fortune, but do not click save and instead clicked a flap on the fortune, the input box stays on the screen. The input box should never be on the screen while after user has clicked a flap. No need to worry about saving here as fortunes save on a flap click.

**Comment by AlbertXDing** [comment]
I fixed this in an old branch. It is fixed again in the [aesthetics-and-bonus-features](https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/tree/aesthetics-and-bonus-features) branch.
