### ISSUE TITLE
Correct input box location

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#70]
Move the input box for changing sidebar fortunes in between the bottom of the fortune teller and the new sidebar at the bottom.

**Comment by phentos** [comment]
one way to easily get multi-line in the input box would be to use a `<textarea>` ([mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea))

**Comment by phentos** [comment]
for the input box location, i think we should fix it to some offset off of the origami itself, like centered 100px below etc

**Comment by adarsh249** [comment]
believe this is changed in parth's new PR, if we agree with this, i can close this issue when merging his PR, please lmk
