### ISSUE TITLE
Implement line wrapping for fortune bar entries

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/Origami-Fortune-Teller#71]
> @AlbertXDing has limited character input to 35 characters, is there a way so that if u input 35 characters on the sidebar button, that the text creates a new line, instead of going out of the box, essentially adding to the issue. All text input should stay in the button box area.

_Originally posted by @adarsh249 in https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/issues/57#issuecomment-1577194725_

**Comment by phentos** [comment]
good use case for `<textarea>`

**Comment by adarsh249** [comment]
same with this issue, believe we can link this to albert's pr on aesthetics
